---

- hosts: localhost
  gather_facts: no

  vars_files:
    - vars/main.yml
    - vars/match.yml
    - vars/actions.yml
    - vars/outcomes.yml

  tasks:

  - include: "{{ playbook_dir }}/includes/determine_teams.yml"

  - debug:
      msg: "Welcome to this exciting showdown between {{ team.1.name }} and {{ team.2.name }}"

  - include: "{{ playbook_dir }}/includes/innings.yml"
    with_items: "{{ range(1,3)|list }}"
    loop_control:
      loop_var: "innings_number"

  - include: "{{ playbook_dir }}/includes/determine_result.yml"
