---

players:
  - { Name: "Player 1" }
  - { Name: "Player 2" }
  - { Name: "Player 3" }
  - { Name: "Player 4" }
  - { Name: "Player 5" }
  - { Name: "Player 6" }
  - { Name: "Player 7" }
  - { Name: "Player 8" }
  - { Name: "Player 9" }
  - { Name: "Player 10" }
  - { Name: "Player 11" }
